const postgres = require('postgres');
require('dotenv').config({ path: '.env.local' });

const { DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT, DATABASE_NAME } = process.env;
const connectionString = `postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=require`;

const sql = postgres(connectionString);

async function main() {
    try {
        console.log('Creating highlights table...');

        await sql`
            CREATE TABLE IF NOT EXISTS highlights (
                id bigint generated by default as identity primary key,
                title text,
                image jsonb,
                url jsonb, -- The video link (e.g. { url: "...", type: "video" })
                is_premium boolean default false,
                is_published boolean default true,
                created_at timestamptz default now(),
                updated_at timestamptz default now()
            );
        `;

        // Enable RLS and policies (copying from others)
        await sql`ALTER TABLE highlights ENABLE ROW LEVEL SECURITY`;

        await sql`DROP POLICY IF EXISTS "Allow public read" ON highlights`;
        await sql`CREATE POLICY "Allow public read" ON highlights FOR SELECT USING (true)`;

        await sql`DROP POLICY IF EXISTS "Allow public insert" ON highlights`;
        await sql`CREATE POLICY "Allow public insert" ON highlights FOR INSERT WITH CHECK (true)`;

        await sql`DROP POLICY IF EXISTS "Allow public update" ON highlights`;
        await sql`CREATE POLICY "Allow public update" ON highlights FOR UPDATE USING (true)`;

        await sql`DROP POLICY IF EXISTS "Allow public delete" ON highlights`;
        await sql`CREATE POLICY "Allow public delete" ON highlights FOR DELETE USING (true)`;

        console.log('✅ Highlights table created successfully!');
    } catch (e) {
        console.error('❌ Error creating table:', e);
    } finally {
        await sql.end();
    }
}

main();
