require('dotenv').config({ path: '.env.local' });
const postgres = require('postgres');

const { DATABASE_URL, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT, DATABASE_NAME } = process.env;

let connectionString = DATABASE_URL;
if (!connectionString && DATABASE_USERNAME && DATABASE_PASSWORD && DATABASE_HOST) {
    connectionString = `postgres://${DATABASE_USERNAME}:${encodeURIComponent(DATABASE_PASSWORD)}@${DATABASE_HOST}:${DATABASE_PORT || 5432}/${DATABASE_NAME || 'postgres'}?sslmode=require`;
}

if (!connectionString) {
    console.error('DATABASE_URL is not set');
    process.exit(1);
}

const sql = postgres(connectionString, { ssl: { rejectUnauthorized: false } });

async function migrate() {
    console.log('Applying Payment Requests & Discounts Schema...');

    try {
        // 1. Add sale_price to packages
        console.log('Adding sale_price to packages...');
        await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS sale_price numeric DEFAULT NULL`;
        console.log('✅ Added sale_price.');

        // 2. Create payment_requests table
        console.log('Creating payment_requests table...');
        await sql`
            CREATE TABLE IF NOT EXISTS payment_requests (
                id bigint generated by default as identity primary key,
                user_id text not null, -- Firebase UID
                package_id bigint references packages(id),
                receipt_image jsonb,
                status text default 'pending', -- pending, approved, rejected
                created_at timestamptz default now(),
                updated_at timestamptz default now()
            )
        `;
        console.log('✅ Created payment_requests table.');

        // 3. RLS Policies
        await sql`ALTER TABLE payment_requests ENABLE ROW LEVEL SECURITY`;

        try { await sql`DROP POLICY IF EXISTS "Allow public read" ON payment_requests`; } catch (e) { }
        try { await sql`DROP POLICY IF EXISTS "Allow public all" ON payment_requests`; } catch (e) { }

        await sql`CREATE POLICY "Allow public read" ON payment_requests FOR SELECT USING (true)`;
        await sql`CREATE POLICY "Allow public all" ON payment_requests FOR ALL USING (true) WITH CHECK (true)`;

        console.log('✅ Applied policies.');
        console.log('🎉 Migration Complete!');
    } catch (e) {
        console.error('❌ Migration Failed:', e);
    } finally {
        await sql.end();
    }
}

migrate();
