require('dotenv').config({ path: '.env.local' });
const postgres = require('postgres');

const { DATABASE_URL, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT, DATABASE_NAME } = process.env;

let connectionString = DATABASE_URL;
if (!connectionString && DATABASE_USERNAME && DATABASE_PASSWORD && DATABASE_HOST) {
    connectionString = `postgres://${DATABASE_USERNAME}:${encodeURIComponent(DATABASE_PASSWORD)}@${DATABASE_HOST}:${DATABASE_PORT || 5432}/${DATABASE_NAME || 'postgres'}?sslmode=require`;
}

if (!connectionString) {
    console.error('DATABASE_URL is not set');
    process.exit(1);
}

const sql = postgres(connectionString, { ssl: { rejectUnauthorized: false } });

async function migrate() {
    try {
        console.log('Starting Advanced Subscription Migration...');

        // 1. PACKAGES
        console.log('Creating packages table...');
        await sql`
      create table if not exists packages (
        id bigint generated by default as identity primary key,
        name text not null,
        description text,
        price numeric not null default 0,
        duration_days integer not null default 30,
        features jsonb default '[]'::jsonb,
        is_active boolean default true,
        created_at timestamptz default now(),
        updated_at timestamptz default now()
      )
    `;
        await sql`alter table packages enable row level security`;
        // Policies
        try { await sql`drop policy if exists "Allow public read" on packages`; } catch (e) { }
        try { await sql`drop policy if exists "Allow public all" on packages`; } catch (e) { }
        await sql`create policy "Allow public read" on packages for select using (true)`;
        await sql`create policy "Allow public all" on packages for all using (true) with check (true)`;


        // 2. PROMO CODES
        console.log('Creating promo_codes table...');
        await sql`
      create table if not exists promo_codes (
        code text primary key,
        discount_percent integer not null default 0,
        max_uses integer default -1,
        used_count integer default 0,
        expires_at timestamptz,
        is_active boolean default true,
        created_at timestamptz default now()
      )
    `;
        await sql`alter table promo_codes enable row level security`;
        // Policies
        try { await sql`drop policy if exists "Allow public read" on promo_codes`; } catch (e) { }
        try { await sql`drop policy if exists "Allow public all" on promo_codes`; } catch (e) { }
        await sql`create policy "Allow public read" on promo_codes for select using (true)`;
        await sql`create policy "Allow public all" on promo_codes for all using (true) with check (true)`;


        // 3. PAYMENT METHODS
        console.log('Creating payment_methods table...');
        await sql`
      create table if not exists payment_methods (
        id bigint generated by default as identity primary key,
        name text not null,
        number text,
        instructions text,
        image jsonb,
        is_active boolean default true,
        created_at timestamptz default now(),
        updated_at timestamptz default now()
      )
    `;
        await sql`alter table payment_methods enable row level security`;
        // Policies
        try { await sql`drop policy if exists "Allow public read" on payment_methods`; } catch (e) { }
        try { await sql`drop policy if exists "Allow public all" on payment_methods`; } catch (e) { }
        await sql`create policy "Allow public read" on payment_methods for select using (true)`;
        await sql`create policy "Allow public all" on payment_methods for all using (true) with check (true)`;


        // 4. USERS UPDATE
        console.log('Updating users table...');
        // We only add columns if they don't exist. "create table if not exists" won't modify existing tables.
        // So we use ALTER TABLE ADD COLUMN IF NOT EXISTS logic (Postgres 9.6+ supports IF NOT EXISTS)

        await sql`alter table users add column if not exists plan_id bigint references packages(id)`;
        await sql`alter table users add column if not exists status text default 'active'`;
        await sql`alter table users add column if not exists joined_at timestamptz default now()`;

        console.log('Migration completed successfully.');

    } catch (err) {
        console.error('Migration failed:', err);
    } finally {
        await sql.end();
    }
}

migrate();
