-- Enable UUID extension if needed (good practice, though we use integers mostly)
create extension if not exists "uuid-ossp";

-- 1. CHANNELS
create table if not exists channels (
  id bigint generated by default as identity primary key,
  name text not null,
  stream_link jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. CATEGORIES
create table if not exists channel_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  is_premium boolean default false,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. RELATIONS (Channels <-> Categories)
create table if not exists _rel_channels_categories (
  id bigint generated by default as identity primary key,
  channel_id bigint references channels(id) on delete cascade,
  category_id bigint references channel_categories(id) on delete cascade,
  unique (channel_id, category_id)
);

-- 4. MATCHES
create table if not exists matches (
  id bigint generated by default as identity primary key,
  team_a text not null,
  team_b text not null,
  logo_a jsonb,
  logo_b jsonb,
  match_time text not null,
  channel text,
  commentator text,
  champion text,
  stream_link jsonb,
  is_premium boolean default false,
  is_published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. GOALS
create table if not exists goals (
  id bigint generated by default as identity primary key,
  title text,
  image jsonb,
  url jsonb,
  time text,
  is_premium boolean default false,
  is_published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 6. NEWS
create table if not exists news (
  id bigint generated by default as identity primary key,
  title text,
  image jsonb,
  link jsonb,
  date text,
  is_premium boolean default false,
  is_published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table channels enable row level security;
alter table channel_categories enable row level security;
alter table _rel_channels_categories enable row level security;
alter table matches enable row level security;
alter table goals enable row level security;
alter table news enable row level security;

-- Open Access Policies (for development/admin - tighten for production!)

-- CHANNELS
drop policy if exists "Allow public read" on channels;
create policy "Allow public read" on channels for select using (true);
drop policy if exists "Allow public insert" on channels;
create policy "Allow public insert" on channels for insert with check (true);
drop policy if exists "Allow public update" on channels;
create policy "Allow public update" on channels for update using (true);
drop policy if exists "Allow public delete" on channels;
create policy "Allow public delete" on channels for delete using (true);

-- CATEGORIES
drop policy if exists "Allow public read" on channel_categories;
create policy "Allow public read" on channel_categories for select using (true);
drop policy if exists "Allow public insert" on channel_categories;
create policy "Allow public insert" on channel_categories for insert with check (true);
drop policy if exists "Allow public update" on channel_categories;
create policy "Allow public update" on channel_categories for update using (true);
drop policy if exists "Allow public delete" on channel_categories;
create policy "Allow public delete" on channel_categories for delete using (true);

-- RELATIONS
drop policy if exists "Allow public read" on _rel_channels_categories;
create policy "Allow public read" on _rel_channels_categories for select using (true);
drop policy if exists "Allow public insert" on _rel_channels_categories;
create policy "Allow public insert" on _rel_channels_categories for insert with check (true);
drop policy if exists "Allow public update" on _rel_channels_categories;
create policy "Allow public update" on _rel_channels_categories for update using (true);
drop policy if exists "Allow public delete" on _rel_channels_categories;
create policy "Allow public delete" on _rel_channels_categories for delete using (true);

-- MATCHES
drop policy if exists "Allow public read" on matches;
create policy "Allow public read" on matches for select using (true);
drop policy if exists "Allow public insert" on matches;
create policy "Allow public insert" on matches for insert with check (true);
drop policy if exists "Allow public update" on matches;
create policy "Allow public update" on matches for update using (true);
drop policy if exists "Allow public delete" on matches;
create policy "Allow public delete" on matches for delete using (true);

-- GOALS
drop policy if exists "Allow public read" on goals;
create policy "Allow public read" on goals for select using (true);
drop policy if exists "Allow public insert" on goals;
create policy "Allow public insert" on goals for insert with check (true);
drop policy if exists "Allow public update" on goals;
create policy "Allow public update" on goals for update using (true);
drop policy if exists "Allow public delete" on goals;
create policy "Allow public delete" on goals for delete using (true);

-- NEWS
drop policy if exists "Allow public read" on news;
create policy "Allow public read" on news for select using (true);
drop policy if exists "Allow public insert" on news;
create policy "Allow public insert" on news for insert with check (true);
drop policy if exists "Allow public update" on news;
create policy "Allow public update" on news for update using (true);
drop policy if exists "Allow public delete" on news;
-- 7. PACKAGES
create table if not exists packages (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null default 0,
  duration_days integer not null default 30,
  features jsonb default '[]'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 8. PROMO CODES
create table if not exists promo_codes (
  code text primary key,
  discount_percent integer not null default 0,
  max_uses integer default -1, -- -1 means infinite
  used_count integer default 0,
  expires_at timestamptz,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- 9. PAYMENT METHODS
create table if not exists payment_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  number text, -- e.g. Phone number or Account number
  instructions text,
  image jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 10. USERS (Subscriptions) - Updated
create table if not exists users (
  id text primary key, -- Firebase UID
  email text not null,
  subscription_end timestamptz,
  plan_id bigint references packages(id),
  status text default 'active', -- active, cancelled, banned
  joined_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- POLICIES (Simplistic for now - Allow all operations)
-- Packages
drop policy if exists "Allow public read" on packages; create policy "Allow public read" on packages for select using (true);
drop policy if exists "Allow public all" on packages; create policy "Allow public all" on packages for all using (true) with check (true);

-- Promo Codes
drop policy if exists "Allow public read" on promo_codes; create policy "Allow public read" on promo_codes for select using (true);
drop policy if exists "Allow public all" on promo_codes; create policy "Allow public all" on promo_codes for all using (true) with check (true);

-- Payment Methods
drop policy if exists "Allow public read" on payment_methods; create policy "Allow public read" on payment_methods for select using (true);
drop policy if exists "Allow public all" on payment_methods; create policy "Allow public all" on payment_methods for all using (true) with check (true);

-- Users Policies
drop policy if exists "Allow public read" on users; create policy "Allow public read" on users for select using (true);
drop policy if exists "Allow public all" on users; create policy "Allow public all" on users for all using (true) with check (true);
